import base64, os, zipfile, io

ZIP_B64 = """
UEsDBBQAAAAIAP1VjVgAAAAAAAAAAAAAAAAUABwAMDVfVFJBREVfQ1JJUFRPLzAxX3NjaGVtYS5zcWxV
VAkAAwAAAAAAAAAAAAAAAAAAAAAAgQSwvirIBwBQSwMEFAAACAAH9o1YAAAAAAAAAAAAAAAAEwAcADAw
NV9UUlFERV9DUklQVE8vMDJfY29uZmlnLnB5VVQJAAMAAAAAAAAAAAAAAAAAAAAAAACBBLArIMAHAFBL
AwQUAAAIAAf2jVgAAAAAAAAAAAAAAAAVABwAMDVfVFJBREVfQ1JJUFRPLzAzX2JvdF9jb3JlLnB5VVQJ
AAMAAAAAAAAAAAAAAAAAAAAAAACBBLArwsAHAFBLAwQUAAAIAAf2jVgAAAAAAAAAAAAAAAAWABwAMDVf
VFJBREVfQ1JJUFRPLzA0X2JvdF9icmFpbi5weVVUCQADAAAAAAAAAAAAAAAAAAAAAAAggQSwK8TABwBQ
SwMEFAAACAAH9o1YAAAAAAAAAAAAAAAADQAcADA1X3J1bl9ib3QucHlVVAkAAwAAAAAAAAAAAAAAAAAA
AAAAAIEEMCsgwAcAUEsBAhQDFAAAAAgA/VWNWAAAAAAAAAAAAAAAABQAHAAAAAAAAAAAAAAAAAAAAAAB
MDVfVFJBREVfQ1JJUFRPLzAxX3NjaGVtYS5zcWxVVAUAAwAAAAAAAAAAAAAAAFBLAQIUAxQAAAgAB/aN
WAAAAAAAAAAAAAAAABMAHAAAAAAAAAAAAAAAAAAAAAAAQTA1X1RSQURFX0NSSVBUTy8wMl9jb25maWcu
cHlVVAUAAwAAAAAAAAAAAAAAAFBLAQIUAxQAAAgAB/aNWAAAAAAAAAAAAAAAABUAHAAAAAAAAAAAAAAA
AAAAAAAAQTA1X1RSQURFX0NSSVBUTy8wM19ib3RfY29yZS5weVVUBQADAAAAAAAAAAAAAAAApQSwEC
FAMUAAAIAAf2jVgAAAAAAAAAAAAAAAAWABwAAAAAAAAAAAAAAAAAAAAAAEEwNV9UUkFERV9DUklQVE8v
MDRfYm90X2JyYWluLnB5VVQFAAOAAAAAAAAAAAAAAAClBLAQIUAxQAAAgAB/aNWAAAAAAAAAAAAAAAAA0A
HAAAAAAAAAAAAAAAAAAAAAAAQTA1X3J1bl9ib3QucHlVVAUAAwAAAAAAAAAAAAAAAFBLBQYAAAAABQAF
AFQBAAAlAQAAAAA=
"""

# Decodificar y extraer
data = base64.b64decode(ZIP_B64.strip())
z = zipfile.ZipFile(io.BytesIO(data))
z.extractall(".")
print("✅ Archivos extraídos correctamente")

# Verificar
for f in ["05_TRADE_CRIPTO/01_schema.sql", "05_TRADE_CRIPTO/02_config.py",
          "05_TRADE_CRIPTO/03_bot_core.py", "05_TRADE_CRIPTO/04_bot_brain.py",
          "05_run_bot.py"]:
    if os.path.exists(f):
        print(f"   ✅ {f}")
    else:
        print(f"   ❌ {f} NO ENCONTRADO")
